### ISSUE TITLE
greenmail.disable property doesn't work propely

### ISSUE THREAD

**Issue by rgorzkowski** [gpc/greenmail#27]
I set grails.plugin.greenmail.disabled=true .
I'm getting NPE exception when I try to access http://localhost:8080/greenmail/list
```
Caused by: java.lang.NullPointerException: Cannot invoke method getReceivedMessages() on null object
	at com.piragua.greenmail.GreenmailController$_list_closure1$_closure4.doCall(GreenmailController.groovy:30)
	at org.grails.plugins.web.api.MimeTypesApiSupport.getResponseForFormat(MimeTypesApiSupport.groovy:142)
	at org.grails.plugins.web.api.MimeTypesApiSupport.resolveAllFormat(MimeTypesApiSupport.groovy:103)
	at org.grails.plugins.web.api.MimeTypesApiSupport.withFormatInternal(MimeTypesApiSupport.groovy:52)
	at org.grails.plugins.web.api.MimeTypesApiSupport.withFormat(MimeTypesApiSupport.groovy:44)
	at grails.artefact.Controller$Trait$Helper.withFormat(Controller.groovy:92)
	at com.piragua.greenmail.GreenmailController.list(GreenmailController.groovy:28)
	... 38 common frames omitted
```

**Comment by rgorzkowski** [comment]
Here is my workaround:
1. I'm setting grails.plugin.greenmail.disabled=false in application.groovy
2. I'm setting 
```groovy
if (Environment.current == Environment.DEVELOPMENT) {
            //greenmail (in-memory smtp for dev purposes)
            "/greenmail/$action?/$id?(.$format)?"(controller: 'greenmail')
}
```
in UrlMappings.groovy file.
